### ISSUE TITLE
In progress?

### ISSUE THREAD

**Issue by johnknoop** [rickardlindgren/BgMax#1]
Hi Rickard

Is this library really complete? Some of the classes like Avsnitt are blank. It would be nice if you could finish this project, then we would happily use it instead of writing our own bgmax parser.

Cheers

**Comment by rickardlindgren** [comment]
Hi!

This is not yet a completed project. I have some local changes not checked in yet but it's progressing slowly. 

Check back in a few days and I'll put up the latest version.
/Rickard

On tor, sep 10, 2015 at 16:51, johnknoop  wrote: Hi Rickard
 Is this library really complete? Some of the classes like Avsnitt are blank. It would be nice if you could finish this project, then we would happily use it instead of writing our own bgmax parser.
 Cheers

**Comment by johnknoop** [comment]
Sure, looking forward to it =)
